### ISSUE TITLE
Timestamp in the handler

### ISSUE THREAD

**Issue by MaKeG0** [malinkinsa/asyncgelf#15]
Hello, 

I've successfully used your library.
I just had to make a modification that could be interesting to add to the default one.

The timestamp parameter

In the GELF documentation there is this parameter that is crucial to have them nicely saved on graylog.

As I've used this library to ingest old logs I wanted to forcefeed the timestamp into the GELF. 

I had to add in the library the timestamp in 
- `def init` with `Optional[int] =None`
- `self.timestamp=timestamp`
- `gelf_message = {... 'timestamp':self.timestamp}`

In my code I've used `int(datetime.strptime(<variable_from_log>, <timeformat>).timestamp())` to get the right format of my original time from the log. It worked.

I was just wondering if there is a more "elegant" way to integrate it in the library.

Thanks

**Comment by malinkinsa** [comment]
Hello,

Thank you for your proposal. Overall, it's quite good. You can go ahead and create the MR, I'll make the changes (if necessary) and promptly verify them. One thing I'd like to note immediately regarding your message is as follows:

- We'll need to include a description for the field, as its value, per the specification, _should be in seconds since the UNIX epoch with optional decimal places for milliseconds_.
- The `gelf_message` field should only be added if the timestamp was provided in the init.

**Comment by MaKeG0** [comment]
Hopefully i've done everything was needed
https://github.com/malinkinsa/asyncgelf/pull/16
Be sure to test it. I've only tested with 1 dataset of 1.5gb and it worked all the way.
I've also added some type checking, i'm sure there is some nicer way to handle the "unix epoch" in a more automatic way

**Comment by malinkinsa** [comment]
Code in master.
You can use it by taking the new version already.

**Comment by MaKeG0** [comment]
> Code in master. You can use it by taking the new version already.

Thanks!

I've already wrote down a draft for the new feature.
I need to test it but the logic is there.
